language: node_js
node_js:
- '0.10'
script:
  - "npm run build"
after_success:
  - echo \!node_modules >> .gitignore
  - "./_travis/deploy-to-ghpages.sh"
env:
  global:
    secure: Lq4E5fPB0uM4pqIbCke6wX4FZ59MxwtpkggGVXQnK4LE59LVCjwN9kltL+1j+Q5aioA5qvuX1U0jr7z5rZxJ/8mFRRBPcKxMpxCbuNjysFAPXVBw0yGUWJuQ+CzrWdx+HKImaVAsnVmKysPzOtnMYtmRDdOjJGJSpxIl3CMfSHY=
